name: Publish snapshot package on commit to main
on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'gradle'
      - name: Execute Gradle build
        run: ./gradlew :core:build
      - name: Echo project version
        run: echo "{project_version}=`./gradlew printVersion --quiet`" >> $GITHUB_ENV
      - name: Delete existing snapshot, if any
        uses: actions/delete-package-versions@v4
        with:
          package-version-ids: ${{ env.project_version }}
          package-name: 'io.github.paulgriffith.kindling.core'
          package-type: 'maven'
        continue-on-error: true
      - name: Publish to Github Packages
        run: ./gradlew :core:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
